# Nombre: firebase-hosting-merge-qa.yml
# Descripción: Despliega la rama qa al sitio de QA (qa-edupilot360) en Firebase Hosting
# Se activa al hacer push a la rama qa

name: Deploy QA to Firebase Hosting

on:
  push:
    branches:
      - qa

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      VITE_FIREBASE_API_KEY: ${{ secrets.QA_VITE_FIREBASE_API_KEY }}
      VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.QA_VITE_FIREBASE_AUTH_DOMAIN }}
      VITE_FIREBASE_PROJECT_ID: ${{ secrets.QA_VITE_FIREBASE_PROJECT_ID }}
      VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.QA_VITE_FIREBASE_STORAGE_BUCKET }}
      VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.QA_VITE_FIREBASE_MESSAGING_SENDER_ID }}
      VITE_FIREBASE_APP_ID: ${{ secrets.QA_VITE_FIREBASE_APP_ID }}
      VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.QA_VITE_FIREBASE_MEASUREMENT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Debug build output
        run: ls -la dist

      - name: Deploy to Firebase Hosting (qa)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ATTENDIFY_APP_KIRPALAMAR }}
          projectId: attendify-app-kirpalamar
          channelId: live
          target: qa

      - name: Notify deployment status (optional)
        run: echo "Deployment to qa completed successfully in Firebase Hosting."
